### ISSUE TITLE
Exploring DevOps: Create tests for our basic application 

### ISSUE THREAD

**Issue by pdvnny** [EC-CS-528-BU-Cloud-Computing/mlops-with-databricks#28]

**Comment by suyash21101** [comment]
created modular code. moving towards completion of entire CI/CD

**Comment by pdvnny** [comment]
This was all good too.

I created some more examples with "pytest" as well if you want to see them.
Link: https://github.com/pdvnny/mlops-databricks-test-env/blob/main/pytest_test.py

**Comment by balajisath** [comment]
Completed. We are using the sorting algorithm as a test in AWS Codestar.
